version: '2'
services:
  db:
    restart: on-failure:10
    image: mysql:5.6
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./data-initdb.d:/docker-entrypoint-initdb.d
      # Uncomment for convenience working with mysql+phpbb
      # - ./public_html/store:/tmp/store
  apache:
    build:
      context: .
      dockerfile: docker/containers/apache.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
  crawler:
    build:
      context: .
      dockerfile: docker/containers/crawler.Dockerfile
    env_file:
      - .env
    volumes:
      - ./mirror.sh:/application/mirror.sh
      - ./archived:/application/archived
    depends_on:
      - apache

